version: '3.4'

services:
  db:
    build: postgres-db/.
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: 'bitnami/redis:latest'
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes

  posts_system:
    build: ./posts-system
    environment:
      - REDIS_URL=redis://redis:6379
      - TOP_POSTS_PAGE_SIZE=30
      - SERVICE_PORT=5000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis
#    volumes:
#      - .:/usr/src/app
