apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-system
spec:
  selector:
    matchLabels:
      app: posts-system
#  replicas: 10
  template:
    metadata:
      labels:
        app: posts-system
    spec:
      containers:
        - image: ronbar/hackernews:v1.01
          name: posts-system
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
          ports:
            - containerPort: 3000
              name: posts-system