apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-system
spec:
  selector:
    matchLabels:
      app: posts-system
#  replicas: 10
  template:
    metadata:
      labels:
        app: posts-system
    spec:
      containers:
        - image: ronbar/hackernews:v1.6
          name: posts-system
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_USER
              value: "postgres"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: TOP_POSTS_PAGE_SIZE
              value: "30"
            - name: SERVICE_PORT
              value: "5000"
          ports:
            - containerPort: 5000
              name: posts-system